// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbtmvwrfahqvyvzuvhom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpidG12d3JmYWhxdnl2enV2aG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODkyNzgsImV4cCI6MjA2NTU2NTI3OH0.d0nro_diOrhCHNZKfRmlkL-pXe3qdYn-72NGULNlgQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);